# Tapster Configuration File
# This file defines how your package should be built and published

name: journal
version: 2.2.0
description: Automatic Git work log generator with AI analysis.
homepage: https://github.com/CalsRanna/auto_reflect
repository: https://github.com/CalsRanna/auto_reflect.git
license: MIT

tap: inspire
asset: build/journal
checksum: e3b5e082f3e3edd6d614e75ecb34016a8516c45711e888141dc057ec32530155
