# Tapster Configuration File
# This file defines how your package should be built and published

name: journal
version: 2.0.0
description: Automatic Git work log generator with AI analysis.
homepage: https://github.com/CalsRanna/auto_reflect
repository: https://github.com/CalsRanna/auto_reflect.git
license: MIT

tap: inspire
asset: build/journal
checksum: da1cd9617820a1822e5d28fbd4316ff291b3cc3eb370dc6042a74f38fdce0060
