# Tapster Configuration File
# This file defines how your package should be built and published

name: journal
version: 2.2.1
description: Automatic Git work log generator with AI analysis.
homepage: https://github.com/CalsRanna/auto_reflect
repository: https://github.com/CalsRanna/auto_reflect.git
license: MIT

tap: inspire
asset: build/journal
checksum: fd81cc876b9910c43fb6458ac4a963169b0e7fdd1dd3903defd7beb8d777a23d
